variable_selection: []
data_dir: "../../data"
out_dir: "image_backbone_exp"
batch_size: 128
num_workers: 0
epochs: 100
lr: 0.0005
weight_decay: 0.0005
label_smoothing: 0.1
early_stopping_patience: 8
var_hidden: 256
dropout: 0.3
num_classes: 17
load_images: true
grad_clip: 1.0
load_checkpoint: false
save_checkpoint: true
use_batchnorm: true
