variable_selection: "all"
data_dir: "../../data"
out_dir: "variables_only"
batch_size: 32
num_workers: 0
epochs: 20
lr: 0.0005
weight_decay: 0.0005
label_smoothing: 0.1
early_stopping_patience: 8
var_hidden: 256
dropout: 0.3
num_classes: 17
load_images: false
grad_clip: 1.0
load_checkpoint: false
save_checkpoint: false
use_batchnorm: true
